algorithm:
  name: "ippo"
  shared:
    num_iterations: 300
    checkpoint_freq: 100
    batch_size: 8000
    num_epochs: 20
    num_minibatches: 10
    learning_rate: 0.0005204479455348368
    num_env_runners: 2
    num_envs_per_env_runner: 10
    num_cpus_per_env_runner: 1
    eval_interval: 5  
    num_eval_episodes: 5  
    evaluation_parallel_to_training: false

  algorithm_specific:
    use_gae: true
    lam: 0.95
    gamma: 0.99
    use_kl_loss: false
    grad_clip: 5.0
    entropy_coeff: 0.004402763769660333
    vf_loss_coeff: 1.1425229102050645
    clip_param: 0.1
    vf_clip_param: 835.4555672655832
    logstd_init: -1.1565544671880936
    logstd_floor: -3.5588934437793998
    obs_normalization: "meanstd_custom"
    parameter_sharing: true
    actor_obs_type: "local"
    critic_obs_type: "local"
    networks:
      shared_layers: null
        #type: "gru"
        #config:
        #  num_layers: 2
        #  hidden_size: 128
        #  bidirectional: false
        #  output_dim: 128
        #  max_seq_len: 20
      use_mu_sigma_head: false
      actor:
        type: "mlp"
        config:        
          hidden_sizes: [256]
          activation: "relu"
          output_activation: null
      critic:
        type: "mlp"
        config:
          hidden_sizes: [256]
          activation: "relu"
          output_activation: null

