algorithm:
  name: "ippo"
  shared:
    num_iterations: 300
    checkpoint_freq: 10
    batch_size: 8000
    num_epochs: 10
    num_minibatches: 20
    learning_rate: 0.0003
    num_env_runners: 4
    num_envs_per_env_runner: 10
    num_cpus_per_env_runner: 1
    eval_interval: 10  
    num_eval_episodes: 5  
    evaluation_parallel_to_training: false

  algorithm_specific:
    use_kl_loss: false
    grad_clip=0.5 
    vf_loss_coeff: 0.5
    vf_clip_param: 1000000
    entropy_coeff: 0.1
    clip_param: 0.2
    use_gae: true
    lam: 0.95
    gamma: 0.99
    obs_normalization: "ratio"
    parameter_sharing: true
    networks:
      shared_layers: null
        #type: "gru"
        #config:
        #  num_layers: 2
        #  hidden_size: 128
        #  bidirectional: false
        #  output_dim: 128
        #  max_seq_len: 20
      actor:
        type: "mlp"
        config:        
          hidden_sizes: [256, 256]
          activation: "relu"
          output_activation: "tanh"
          # output_dim: null
      critic:
        type: "mlp"
        config:
          hidden_sizes: [256, 256]
          activation: "relu"
          output_activation: null
          # output_dim: null

