algorithm:
  name: "ippo"
  shared:
    learning_rate: 0.0003
    batch_size: 4000
    num_iterations: 1000
    checkpoint_freq: 100
  algorithm_specific:
    vf_loss_coeff: 0.5
    entropy_coeff: 0.01
    clip_param: 0.2
    use_gae: true
    lambda: 0.95
    parameter_sharing: false

