algorithm:
  name: "ippo"
  shared:
    num_iterations: 500
    checkpoint_freq: 50
    batch_size: 40000
    num_epochs: 3
    num_minibatches: 4
    learning_rate: 0.001
    num_env_runners: 4
    num_envs_per_env_runner: 10
    num_cpus_per_env_runner: 1
    eval_interval: 10  
    num_eval_episodes: 5  
    evaluation_parallel_to_training: false

  algorithm_specific:
    use_gae: true
    lam: 0.95
    gamma: 0.99
    use_kl_loss: false
    grad_clip: null
    entropy_coeff: 0.01
    vf_loss_coeff: 0.5
    clip_param: 0.2
    vf_clip_param: 300
    obs_normalization: "ratio"
    parameter_sharing: false
    networks:
      shared_layers: null
        #type: "gru"
        #config:
        #  num_layers: 2
        #  hidden_size: 128
        #  bidirectional: false
        #  output_dim: 128
        #  max_seq_len: 20
      use_mu_sigma_head: false
      actor:
        type: "mlp"
        config:        
          hidden_sizes: [128]
          activation: "relu"
          output_activation: null
      critic:
        type: "mlp"
        config:
          hidden_sizes: [128]
          activation: "relu"
          output_activation: null

