algorithm:
  name: "ippo"
  shared:
    num_iterations: 10
    checkpoint_freq: 5
    batch_size: 1200
    num_epochs: 10
    num_minibatches: 4
    learning_rate: 0.0004
    num_env_runners: 0
    num_envs_per_env_runner: 1
    num_cpus_per_env_runner: 1
    eval_interval: 10  
    num_eval_episodes: 5  
    evaluation_parallel_to_training: false

  algorithm_specific:
    vf_loss_coeff: 0.5
    entropy_coeff: 0.01
    clip_param: 0.2
    use_gae: true
    lam: 0.95
    gamma: 0.95
    parameter_sharing: true
    networks:
      shared_layers: null
        #type: "gru"
        #config:
        #  num_layers: 2
        #  hidden_size: 128
        #  bidirectional: false
        #  output_dim: 128
        #  max_seq_len: 20
      actor:
        type: "gru"
        config:
          num_layers: 2
          hidden_size: 128
          bidirectional: false
          output_dim: 128
          max_seq_len: 20
      critic:
        type: "gru"
        config:
          num_layers: 2
          hidden_size: 128
          bidirectional: false
          output_dim: 128
          max_seq_len: 20

