algorithm:
  name: "maddpg"
  rllib_config:
    learning_rate: 0.0001
    batch_size: 64
    gamma: 0.95
    num_workers: 4
    train_batch_size: null
  training:
    num_iterations: 2000
    checkpoint_freq: 200
    evaluation_freq: 100
    evaluation_num_episodes: 10

