algorithm:
  name: "qmix"
  rllib_config:
    learning_rate: 0.0005
    batch_size: 32
    gamma: 0.99
    num_workers: 4
    train_batch_size: null
  training:
    num_iterations: 1000
    checkpoint_freq: 100
    evaluation_freq: 50
    evaluation_num_episodes: 10

